import type { Locale } from "../i18n";
import type { SettingsSection, StepId, StudioSection } from "../types";
export const providerUiCopy = {
  ko: {},
  en: {
    localModeLocalOnlyTitle: "Local only",
    localModeLocalOnlyBody: "Run the assistant only on this computer without internet use.",
    localModeCloudOnlyTitle: "Cloud only",
    localModeCloudOnlyBody: "Start with OpenAI/Gemini/Groq APIs and skip the Ollama install path.",
    localModeHybridTitle: "Local + cloud hybrid",
    localModeHybridBody: "Use local models by default, then add APIs and Google Workspace later.",
    recommended: "Recommended",
    localModels: "Local models",
    cloudModels: "Cloud models",
    bestMatch: "Best match",
    selected: "Selected",
    selectModel: "Select model",
    comingSoon: "Coming soon",
    customOllama: "Custom Ollama model",
    customOllamaBody: "Manual model-name entry will be added in a later step.",
    provider: "Provider",
    providerStatus: "Provider status",
    localHeader: "LOCAL",
    cloudHeader: "CLOUD",
    localDataNotice: "Data stays on this PC.",
    cloudDataNotice: "Messages are sent to the selected external provider.",
    continueToProviderSettings: "Continue to API keys",
    continueToOllama: "Continue to Ollama",
    cloudBackendPending: "Cloud chat routing will be implemented in the next backend step.",
    localRuntimeReady: "Local runtime",
    cloudRuntimeReady: "Cloud provider",
    hasOverride: "Override set",
    needsKey: "Key needed",
    defaultKey: "Demo keys",
    cloudSyncedKey: "Synced from web",
  },
} satisfies Record<Locale, Record<string, string>>;

export const steps: Array<{ id: StepId; label: string; detail: string }> = [
  { id: "welcome", label: "Welcome", detail: "Start" },
  { id: "userProfile", label: "Profile", detail: "About you" },
  { id: "hardware", label: "Hardware", detail: "PC check" },
  { id: "recommendation", label: "Recommendation", detail: "Best model" },
  { id: "ollama", label: "Ollama", detail: "Runtime" },
  { id: "clawCode", label: "Claw Code", detail: "Optional" },
  { id: "download", label: "Download", detail: "Local model" },
  { id: "chat", label: "Chat", detail: "Test" },
];

export const settingsSections: Array<{ id: SettingsSection; label: string; detail: string; icon: string }> = [
  { id: "general", label: "General", detail: "Language, storage, assistant", icon: "settings" },
  { id: "personalization", label: "Personalization", detail: "Global prompt style", icon: "tune" },
  { id: "aiModels", label: "AI models", detail: "Provider, model, API keys", icon: "memory" },
  { id: "clawCode", label: "Claw Code", detail: "Install and workspace folder", icon: "terminal" },
  { id: "logs", label: "Logs", detail: "Local app activity", icon: "article" },
];

export const studioSections: Array<{ id: StudioSection; label: string; detail: string; icon: string }> = [
  { id: "myAssistants", label: "My Assistants", detail: "Saved assistants", icon: "supervisor_account" },
  { id: "assistantStore", label: "Assistant Store", detail: "Shared assistants", icon: "storefront" },
  { id: "overview", label: "Overview", detail: "Assistant build status", icon: "dashboard" },
  { id: "models", label: "Models", detail: "Browse and download", icon: "deployed_code_update" },
  { id: "prompts", label: "Prompts", detail: "Persona and instructions", icon: "edit_note" },
  { id: "character", label: "2D character", detail: "Avatar and expressions", icon: "face" },
  { id: "tts", label: "TTS / Voice", detail: "Speech settings", icon: "record_voice_over" },
  { id: "googleWorkspace", label: "Google Workspace", detail: "Calendar, Gmail, Drive", icon: "workspaces" },
  { id: "code", label: "Code", detail: "Repository access", icon: "code" },
  { id: "skills", label: "Rules & Skills", detail: "Reusable guidance", icon: "menu_book" },
];

export const copy = {
  ko: {},
  en: {
    appSubtitle: "A local setup app for installing and testing an AI assistant on this computer",
    setupMode: "Setup",
    studioMode: "Studio",
    runtimeMode: "Runtime",
    historyMode: "History",
    historyTitle: "Conversation History",
    historyBody: "Browse past chats grouped by date and assistant. Everything stays on this device.",
    historyEmptyTitle: "No conversations yet",
    historyEmptyBody: "Start chatting in Runtime to save conversations here for later.",
    historySearchPlaceholder: "Search chats by title, assistant, or message",
    historyNoResultsTitle: "No matching chats",
    historyNoResultsBody: "Try a different keyword or clear the search to see every conversation.",
    historyMessages: "{count} messages",
    historyConversations: "{count} conversations",
    historyContinueInRuntime: "Continue in Runtime",
    historyViewConversation: "View conversation",
    stopGeneration: "Stop generating",
    attachImage: "Attach image",
    imageVisionNotice: "Attached images are analyzed with Gemini 2.5 Flash.",
    attachmentAnalyzing: "Analyzing…",
    attachmentReady: "Ready",
    attachmentError: "Analysis failed",
    attachmentsAnalyzingNotice: "Still analyzing the attached file — please wait a moment.",
    enterMiVA: "Enter MiVA",
    assistantWorkspace: "Assistant Workspace",
    newChat: "New Chat",
    recentConversations: "Recent Conversations",
    savedSnippets: "Saved Snippets",
    systemLogs: "System Logs",
    backToSetup: "Back to Setup",
    setupFlow: "Setup Flow",
    setupFlowSubtitle: "Initial Setup",
    settings: "Settings",
    localOnly: "Local only",
    language: "Language",
    welcomeTitle: "Welcome to MiVA",
    welcomeBody:
      "Create a private AI workspace that learns how you work.\n\nMIVA helps you configure reusable AI assistants based on your tasks, preferences, and work style. All computation happens locally, keeping your data strictly private.",
    startSetup: "Start Setup",
    estimatedTime: "Estimated time: 5 Minutes",
    continue: "Continue",
    back: "Back",
    privacyTitle: "Private by design",
    privacyBody: "Your setup stays under your control. No data ever leaves your hardware.",
    hardwarePrivacyBody: "Phase 1 runs without login. Profile answers and PC information are only used inside this app for recommendations.",
    localModelTitle: "Built around your work style",
    localModelBody: "MIVA learns how you want AI to answer, adapting to your specific professional context.",
    guidedTitle: "Reusable assistants",
    guidedBody: "Save task-specific AI setups and use them again for complex, recurring workflows.",
    surveyTitle: "What kind of AI assistant do you need?",
    surveyBody: "Pick the closest use case and MiVA will calculate a first recommendation from lightweight models.",
    surveyPageTitle: "Personalize your MiVA",
    surveyProgress: "Question",
    selectOne: "Choose one",
    selectMany: "Choose any that apply",
    previousQuestion: "Previous",
    nextQuestion: "Next",
    nextHardware: "Next: Hardware Check",
    proTipTitle: "Pro Tip",
    proTipBody: "You can change these preferences at any time after setup.",
    advancedOptionsTitle: "Advanced options",
    advancedOptionsBody: "This area will handle detailed AI feature settings. Phase 1 starts with language and local setup policy, then expands into Google Workspace and tool connections.",
    advancedOptionsButton: "Open advanced settings",
    priorityTitle: "What matters most?",
    answerStyleTitle: "What answer style do you prefer?",
    languageUseTitle: "Which language will you use most?",
    localModeTitle: "How do you want to use MiVA?",
    futureFeatureTitle: "Which future features interest you?",
    memorySyncTitle: "How should this assistant continue on other devices?",
    profileOnlyMemory: "Settings sync only",
    profileOnlyMemoryBody: "Sync assistant settings only.",
    summaryMemory: "Summary memory sync",
    summaryMemoryBody: "Sync assistant settings and summary memory.",
    balanced: "Balanced",
    balancedBody: "Balance speed and answer quality.",
    speed: "Speed",
    speedBody: "Prioritize lighter models and short answers.",
    quality: "Answer quality",
    qualityBody: "Prioritize stronger answers even if they are slower.",
    shortAnswer: "Short and direct",
    shortAnswerBody: "Get the point quickly.",
    moderateAnswer: "Moderate explanation",
    moderateAnswerBody: "Include short context when useful.",
    detailedAnswer: "Detailed explanation",
    detailedAnswerBody: "Explain background and steps more fully.",
    koreanMain: "Korean-first",
    koreanMainBody: "Mostly Korean questions and answers.",
    englishMain: "English-first",
    englishMainBody: "Mostly English sources and answers.",
    bilingualMain: "Korean and English",
    bilingualMainBody: "Use both languages depending on context.",
    localOnlyMode: "Local only, no internet",
    localOnlyModeBody: "Keep usage entirely on this computer.",
    localAfterSetupMode: "Local after setup",
    localAfterSetupModeBody: "Download/install first, then run locally.",
    futureIntegrationsMode: "Future integrations are okay",
    futureIntegrationsModeBody: "Google Workspace, APIs, and tools can be added later.",
    voiceFeature: "Voice chat",
    voiceFeatureBody: "Use microphone input and spoken responses.",
    characterFeature: "AI character screen",
    characterFeatureBody: "Configure a visual character later in Studio.",
    googleFeature: "Google Calendar / Gmail",
    googleFeatureBody: "Use Google Workspace as assistant context.",
    filesFeature: "Read documents/files",
    filesFeatureBody: "Use local files as assistant context.",
    toolsFeature: "External tools",
    toolsFeatureBody: "Agent skills and external APIs.",
    unsureFeature: "Not sure yet",
    unsureFeatureBody: "Start with the default local assistant.",
    daily: "Daily planning",
    dailyBody: "A helper for schedules, tasks, and notes",
    study: "Study/Writing",
    studyBody: "A helper for summaries, drafts, and explanations",
    work: "Work support",
    workBody: "A helper for emails, documents, and light analysis",
    fast: "Fast casual chat",
    fastBody: "A quick assistant for low-friction questions",
    character: "Character assistant",
    characterBody: "Start with an assistant that can later receive a Studio character",
    hardwareTitle: "Hardware Check",
    hardwareBody: "Let's see what your machine is capable of. We analyze your system to suggest the best AI models for a smooth experience.",
    scanPc: "Rescan",
    checking: "Checking",
    detected: "Detected",
    unknown: "Unknown",
    processor: "Processor",
    memory: "Memory",
    graphics: "Graphics (GPU)",
    disk: "Disk Space",
    verdict: "Verdict",
    highEnd: "High-End",
    great: "Great",
    good: "Good",
    basic: "Basic",
    limited: "Limited",
    optimal: "Optimal",
    driveDetected: "Drive Detected",
    healthy: "Healthy",
    used: "Used",
    cores: "Cores",
    vramUsage: "VRAM Usage",
    vramPlaceholder: "Pending",
    modelCapacity: "Model Capacity",
    modelCapacityBody: "You have enough space for approx. {count} lightweight local assistant models. Large-model capacity rules are placeholders for now.",
    cpuVerdictHigh: "Excellent for multi-tasking and large-scale local AI inferencing.",
    cpuVerdictGood: "Strong enough for lightweight local assistant models.",
    cpuVerdictBasic: "Suitable for small-model tests, but multitasking may be limited.",
    memoryVerdictGreat: "Plenty of room for running even more complex local models.",
    memoryVerdictGood: "Enough memory for lightweight local assistant models.",
    memoryVerdictLimited: "Start with ultralight models first.",
    gpuVerdictDetected: "GPU detected, but VRAM is still a placeholder. A future VRAM check will make recommendations more precise.",
    gpuVerdictMissing: "Dedicated GPU details were not detected. Phase 1 recommendations use CPU and RAM first.",
    gpuMissing: "Missing",
    noSupportedGpu: "No supported GPU detected",
    systemVerificationComplete: "System Verification Complete",
    hardwareMinimumMet: "Basic checks for the MiVA Phase 1 local assistant are complete.",
    continueRecommendations: "Continue to Recommendations",
    totalRam: "Total RAM",
    available: "Available",
    recommendationTitle: "Recommended model",
    recommendationBody: "This first model choice is based on the default MiVA profile and current PC information.",
    recommendationReadyTitle: "Model selection ready",
    recommendationReadyBody: "Continue when you're happy with the selected model, or pick another option below.",
    selectThis: "Use this model",
    alternatives: "Alternative models",
    ollamaTitle: "Ollama runtime",
    ollamaBody: "MiVA uses Ollama as the local model runner. Ollama is not the model; it is the program that runs models.",
    installOllama: "Install Ollama",
    startOllama: "Start Ollama",
    refresh: "Refresh",
    running: "Running",
    stopped: "Installed, not running",
    missing: "Needs install",
    activity: "Activity",
    noLogs: "No activity yet.",
    ollamaReadyTitle: "Ollama is running",
    ollamaReadyBody: "The local runtime is ready. You can continue to the next setup step.",
    ollamaPendingTitle: "Ollama not ready",
    ollamaPendingBody: "Install and start Ollama before continuing.",
    downloadTitle: "Download model",
    downloadBody: "Download the selected model into Ollama's default model storage. Phase 1 does not customize storage paths.",
    downloadModel: "Download model",
    downloading: "Downloading...",
    downloadProgressTitle: "Downloading model",
    preparingDownload: "Preparing download",
    downloadComplete: "Download complete",
    downloadReadyBody: "The selected model is installed and ready for chat testing.",
    downloadPendingTitle: "Model download required",
    downloadPendingBody: "Download the selected model before continuing.",
    downloadFailed: "Download failed",
    close: "Close",
    downloaded: "Downloaded",
    downloadSize: "Download size",
    minimizeDownload: "Minimize",
    expandDownload: "Expand",
    collapseDownload: "Collapse",
    pauseDownload: "Pause",
    resumeDownload: "Resume",
    stopDownload: "Stop",
    stopDownloadConfirmTitle: "Stop this download?",
    stopDownloadConfirmBody: "This cancels the download and removes any partial files that were already received.",
    keepDownloading: "Keep downloading",
    confirmStopDownload: "Stop download",
    downloadPaused: "Download paused",
    downloadCancelled: "Download cancelled",
    installed: "Installed",
    notInstalled: "Not installed",
    modelStorage: "Storage",
    defaultStorage: "Use Ollama's default model storage",
    chatTitle: "Local chat test",
    chatBody: "After the model is installed, confirm MiVA responds locally.",
    chatSandboxTitle: "Test Chat",
    chatSandboxBody: "Use this temporary chat to test the selected assistant before entering Runtime.",
    chatGreeting: "Hello! I'm your local AI assistant running on MiVA. I've successfully loaded the {model} model into your local memory. How can I help you today?",
    assistantStageTitle: "Assistant Runtime",
    assistantStageBody: "The future MiVA runtime space for chat, voice, and character expression.",
    characterPreview: "Character Preview",
    characterPreviewBody: "Phase 1 shows status expression only. Live2D and voice reactions will be connected later.",
    characterIdle: "Idle",
    clawCodeReadyTitle: "Optional step complete",
    clawCodeReadyBody: "You can install Claw Code now or later from Settings > Claw Code.",
    characterListening: "Waiting for input",
    localRuntime: "Local Runtime",
    generatingResponse: "Generating response...",
    jumpToLatest: "Jump to latest chat",
    justNow: "Just now",
    suggestedAction: "Suggested Action",
    suggestedPrompt: "Tell me a short story about a helpful robot.",
    latencyMetric: "Latency: 45ms",
    tokensMetric: "Tokens: 12.4 t/s",
    vramMetric: "VRAM: Pending",
    messagePlaceholder: "Ask MiVA something...",
    send: "Send",
    noMessages: "No messages yet.",
    runtimeRequired: "Local commands only work inside the Tauri desktop window.",
    settingsTitle: "App settings",
    settingsBody: "Manage language, local model policy, and external AI provider keys. Secure storage comes before distribution.",
    currentModel: "Current model",
    serviceStatus: "Service status",
    installedModels: "Installed models",
    providerKeysTitle: "AI Provider Keys",
    providerKeysBody: "When signed in, API keys saved in the web console sync here automatically. Leave fields empty to use synced web keys or bundled demo keys. Enter a key to save a local override for this app.",
    openaiApiKey: "OpenAI API Key",
    geminiApiKey: "Gemini API Key",
    groqApiKey: "Groq API Key",
    userOverrideKey: "User override key",
    defaultEnvKey: "Use demo keys",
    saveKeys: "Save keys",
    clearKeys: "Clear keys",
    keysSaved: "Saved locally",
    keyStorageNotice: "This currently uses localStorage for development testing. Replace it with OS secure storage before distribution.",
    none: "None",
  },
} satisfies Record<Locale, Record<string, string>>;

export type CopyKey = keyof (typeof copy)["en"];

export type SurveyOption = {
  id: string;
  titleKey?: CopyKey;
  bodyKey?: CopyKey;
  title?: Record<Locale, string>;
  body?: Record<Locale, string>;
  icon: string;
};

export type SurveyQuestionId = "useCase" | "answerStyle" | "priority" | "languageUse" | "localMode" | "futureFeatures" | "memorySyncMode";

export type SurveyQuestion = {
  id: SurveyQuestionId;
  titleKey: CopyKey;
  helperKey: CopyKey;
  multi: boolean;
  columns: string;
  options: SurveyOption[];
};

const useCaseCards: SurveyOption[] = [
  { id: "daily", titleKey: "daily", bodyKey: "dailyBody", icon: "event_note" },
  { id: "study", titleKey: "study", bodyKey: "studyBody", icon: "edit_note" },
  { id: "work", titleKey: "work", bodyKey: "workBody", icon: "work_outline" },
  { id: "fast", titleKey: "fast", bodyKey: "fastBody", icon: "forum" },
  { id: "character", titleKey: "character", bodyKey: "characterBody", icon: "smart_toy" },
];

const answerStyleOptions: SurveyOption[] = [
  { id: "short", titleKey: "shortAnswer", bodyKey: "shortAnswerBody", icon: "bolt" },
  { id: "moderate", titleKey: "moderateAnswer", bodyKey: "moderateAnswerBody", icon: "subject" },
  { id: "detailed", titleKey: "detailedAnswer", bodyKey: "detailedAnswerBody", icon: "article" },
];

const priorityOptions: SurveyOption[] = [
  { id: "balanced", titleKey: "balanced", bodyKey: "balancedBody", icon: "tune" },
  { id: "speed", titleKey: "speed", bodyKey: "speedBody", icon: "speed" },
  { id: "quality", titleKey: "quality", bodyKey: "qualityBody", icon: "auto_awesome" },
];

const languageUseOptions: SurveyOption[] = [
  { id: "korean", titleKey: "koreanMain", bodyKey: "koreanMainBody", icon: "translate" },
  { id: "english", titleKey: "englishMain", bodyKey: "englishMainBody", icon: "language" },
  { id: "both", titleKey: "bilingualMain", bodyKey: "bilingualMainBody", icon: "forum" },
];

const localModeOptions: SurveyOption[] = [
  {
    id: "localOnly",
    title: {
      ko: "Korean copy pending",
      en: providerUiCopy.en.localModeLocalOnlyTitle,
    },
    body: {
      ko: "Korean copy pending",
      en: providerUiCopy.en.localModeLocalOnlyBody,
    },
    icon: "lock",
  },
  {
    id: "cloudOnly",
    title: {
      ko: "Korean copy pending",
      en: providerUiCopy.en.localModeCloudOnlyTitle,
    },
    body: {
      ko: "Korean copy pending",
      en: providerUiCopy.en.localModeCloudOnlyBody,
    },
    icon: "cloud",
  },
  {
    id: "hybrid",
    title: {
      ko: "Korean copy pending",
      en: providerUiCopy.en.localModeHybridTitle,
    },
    body: {
      ko: "Korean copy pending",
      en: providerUiCopy.en.localModeHybridBody,
    },
    icon: "hub",
  },
];

const futureFeatureOptions: SurveyOption[] = [
  { id: "voice", titleKey: "voiceFeature", bodyKey: "voiceFeatureBody", icon: "mic" },
  { id: "character", titleKey: "characterFeature", bodyKey: "characterFeatureBody", icon: "smart_toy" },
  { id: "googleWorkspace", titleKey: "googleFeature", bodyKey: "googleFeatureBody", icon: "calendar_month" },
  { id: "files", titleKey: "filesFeature", bodyKey: "filesFeatureBody", icon: "folder_open" },
  { id: "tools", titleKey: "toolsFeature", bodyKey: "toolsFeatureBody", icon: "extension" },
  { id: "unsure", titleKey: "unsureFeature", bodyKey: "unsureFeatureBody", icon: "help" },
];

const memorySyncOptions: SurveyOption[] = [
  { id: "profileOnly", titleKey: "profileOnlyMemory", bodyKey: "profileOnlyMemoryBody", icon: "sync" },
  { id: "summaryMemory", titleKey: "summaryMemory", bodyKey: "summaryMemoryBody", icon: "memory" },
];

export const surveyQuestions: SurveyQuestion[] = [
  { id: "useCase", titleKey: "surveyTitle", helperKey: "selectOne", multi: false, columns: "grid-cols-2 xl:grid-cols-3", options: useCaseCards },
  { id: "answerStyle", titleKey: "answerStyleTitle", helperKey: "selectOne", multi: false, columns: "grid-cols-3", options: answerStyleOptions },
  { id: "priority", titleKey: "priorityTitle", helperKey: "selectOne", multi: false, columns: "grid-cols-3", options: priorityOptions },
  { id: "languageUse", titleKey: "languageUseTitle", helperKey: "selectOne", multi: false, columns: "grid-cols-3", options: languageUseOptions },
  { id: "localMode", titleKey: "localModeTitle", helperKey: "selectOne", multi: false, columns: "grid-cols-3", options: localModeOptions },
  { id: "memorySyncMode", titleKey: "memorySyncTitle", helperKey: "selectOne", multi: false, columns: "grid-cols-2", options: memorySyncOptions },
  { id: "futureFeatures", titleKey: "futureFeatureTitle", helperKey: "selectMany", multi: true, columns: "grid-cols-2 xl:grid-cols-3", options: futureFeatureOptions },
];

